Reporting
SevenTV/GQL pull request #11
Opened 2021-11-15 21:45 UTC by AnatoleAM

Adding queries and mutations for user/emote reporting

2021-11-16 19:46 UTC, TroyDota requested changes
Can you walk me through the design and why you made the choices you did?

2021-11-16 19:46 UTC, TroyDota commented on src/configure/collections.go
> +var Indexes = []mongo.IndexRef{
why is this a global variable?

2021-11-16 19:46 UTC, TroyDota commented on src/server/v3/schema/reports.gql
> +}
add new line at end of file.

2021-11-17 23:45 UTC, AnatoleAM commented
@TroyDota, on the design:

Reports are structured with a `target_kind` value denoting the type of object being reported (i.e a user or an emote). The report contains two text fields, a `subject` field which contains the complaint (i.e "My emote was stolen") and `body` which allows adding extra information, such as evidence.

Reports can also have assignees (i.e a moderator) and a priority (for example to give special priority to some users). 
Furthermore this implements a "notes" system, which allows quick communication with the reporter.

2021-11-17 23:47 UTC, AnatoleAM commented on src/configure/collections.go
> +var Indexes = []mongo.IndexRef{
Referenced in `main.go` to set up indexes

2021-11-18 20:51 UTC, merged