WebSocket Transport
SevenTV/GQL pull request #24
Opened 2022-02-16 12:21 UTC by AnatoleAM

Implementing the WebSocket transport for GQL

2022-02-19 11:26 UTC, TroyKomodo requested changes

2022-02-19 11:26 UTC, TroyKomodo commented on models/struct.go
> +
what is this?

2022-02-19 11:26 UTC, TroyKomodo commented on schema/bans.gql
> +  victim: User! @goField(forceResolver: true)
remove `!` from these

2022-02-19 11:26 UTC, TroyKomodo commented on schema/roles.gql
> +  members: [User!]! @goField(forceResolver: true)
bad idea

2022-02-19 11:26 UTC, TroyKomodo commented on schema/users.gql
> +  connections(id: String!, data: UserConnectionUpdate!): [UserConnection]
what is this for?

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +// var json = jsoniter.ConfigCompatibleWithStandardLibrary
remove comment

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.emoteset.go
> +	ch := make(chan *model.EmoteSet, 1)
i think this channel needs to be closed?

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.emote.go
> +	emote, err := getEmote()
You dont check the value of init

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.emote.go
> +	ch := make(chan *model.EmotePartial, 1)
this channel needs to be closed

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.emote.go
> +		for range sub {
you can do `defer close(ch)`

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.emoteset.go
> +		sub := r.subscribe(ctx, "emote_sets", id)
you can do `defer close(ch)`

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +	ch := make(chan *model.UserPartial, 1)
this channel needs to close

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +	user, err := getUser()
why fetch the object if we dont use it when init is false?

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +	user, err := getUser()
why fetch the object if we dont use it

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +	ch := make(chan *model.UserPartial, 1)
channel needs to close

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +	go func() {
you can do `defer close(ch)`

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +	go func() {
you can do `defer close(ch)`

2022-02-19 11:26 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/subscription.go
> +	ch := make(chan string, 1)
why are u making 2 channels?

2022-02-19 11:26 UTC, TroyKomodo commented on main.go
> +		gCtx.Inst().Redis = redisInst
why are we not wrapping redis anymore?

2022-02-19 20:00 UTC, AnatoleAM commented on main.go
> +		gCtx.Inst().Redis = redisInst
Because the wrapped redis is in Common, I dunno why we had extraneous interfaces in individual repos

2022-02-19 20:01 UTC, AnatoleAM commented on schema/bans.gql
> +  victim: User! @goField(forceResolver: true)
I only re-ordered these, i didn't actually write these schemas. Can review the nullability of everything later

2022-02-19 20:02 UTC, AnatoleAM commented on schema/users.gql
> +  connections(id: String!, data: UserConnectionUpdate!): [UserConnection]
Updating a user connection. Right now for editing the active emote set of a connection

2022-02-19 20:10 UTC, AnatoleAM commented on src/api/v3/gql/resolvers/subscription/subscription.go
> +	ch := make(chan string, 1)
Because the original channel is occupied by the context cancellation check, so 1/2 events would be skipped

2022-02-20 19:39 UTC, TroyKomodo requested changes

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/loaders/emoteset.loader.go
> +				for _, set := range v.Sets {
what are u trying to do here?

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/loaders/emoteset.loader.go
> +				for _, set := range v.Sets {
same here

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.emote.go
> +			return nil, err
channel leak

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.emoteset.go
> +		if err != nil {
channel leak

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +		if err != nil {
channel leak

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +			return nil, err
channel leak

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/middleware/auth.go
> +	_, claims, err := auth.VerifyJWT(ctx.Config().Credentials.JWTSecret, strings.Split(t, "."))
can this claims object not be a struct?

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/user/user.partial.go
> +	result := make([]*model.Role, 0, len(m))
why are u making an array this way?

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/user/user.partial.go
> +	result := make([]*model.Role, 0, len(m))
`make([]*model.Role, len(m))`

2022-02-20 19:39 UTC, TroyKomodo commented on src/api/v3/gql/resolvers/user/user.go
> +	result := make([]*model.Role, 0, len(m))
Why are u making an array this way?
`make([]*model.Role, len(m))`

2022-02-20 19:43 UTC, AnatoleAM commented on src/api/v3/gql/resolvers/subscription/sub.user.go
> +			return nil, err
where?

2022-02-20 20:25 UTC, AnatoleAM commented on src/api/v3/gql/loaders/emoteset.loader.go
> +				for _, set := range v.Sets {
Constructing the full value, since I flattened the aggregations. Instead of building relational data in the pipeline, I instead do a lookup on every related object and link them together in code. This is **insanely** faster

2022-02-21 18:46 UTC, TroyKomodo reviewed
We should also change the gql schema to make the members field pageable

2022-02-21 18:47 UTC, TroyKomodo requested changes

2022-02-21 18:47 UTC, TroyKomodo commented on schema/bans.gql
> +  victim: User! @goField(forceResolver: true)
Lets drop the ! here

2022-02-21 18:47 UTC, TroyKomodo commented on schema/bans.gql
> +  actor: User! @goField(forceResolver: true)
Lets drop the ! here

2022-02-21 18:47 UTC, TroyKomodo commented on schema/roles.gql
> +  members: [User!]! @goField(forceResolver: true)
Lets make this a function that takes in a page and a limit.

2022-02-21 18:52 UTC, AnatoleAM commented on schema/bans.gql
> +  actor: User! @goField(forceResolver: true)
This should be done on another branch, since this is about the websocket transport - these diffs are ordering only when I added the `Subscription` extensions, I moved all the operation declarations at the top

2022-02-22 10:49 UTC, merged