Quota Rate Limiting
SevenTV/GQL pull request #6
Opened 2021-10-18 13:43 UTC by AnatoleAM

Creating a rate limiter for GQL which uses a Quota system rather than a conventional request-based rate limit.

Each request is granted a quota, with a specific number of points. Each queried field decreases the points by a set amount. For calls to the same object, the point cost is less, while relational calls will cost more. Ultimately, if the amount of points remaining reaches zero, the request is rejected with status `429 Too Many Requests` and information about the quota.

This adds the following headers to requests:
- `X-Quota-Limit` is the initial amount of points in the Quota
- `X-Quota-Remaining` is the amount of points left over after the request (may be negative if exceeded)
- `X-Quota-Usage` offers details about each queried fields and their quota costs as a JSON map.

2021-10-18 21:29 UTC, TroyDota commented on src/configure/config.go
> +
Extra newline?

2021-10-18 21:30 UTC, TroyDota commented on src/server/v3/gql-v3.go
> +		h.Write(utils.S2B(strings.Map(func(r rune) rune {
What does this do?

2021-10-18 21:32 UTC, TroyDota commented on src/server/v3/helpers/errors.go
> +package helpers
What does this file do?

2021-10-18 21:32 UTC, TroyDota commented on src/server/v3/helpers/keys.go
> +package helpers
You actually dont need these.

2021-10-18 21:33 UTC, TroyDota commented on src/server/v3/helpers/quota.go
> +func (q *Quota) DecreaseByOne(object string, field string) bool {
You actually can do this via atomic, without using a mxtx, you can do where limit and Points are both pointers and then use atomic.AddInt32 or smth

2021-10-19 06:58 UTC, AnatoleAM commented on src/server/v3/gql-v3.go
> +		h.Write(utils.S2B(strings.Map(func(r rune) rune {
Gonna leave this for now until we have a better way of building the hash

2021-10-19 07:16 UTC, TroyDota requested changes

2021-10-19 07:16 UTC, TroyDota commented on src/server/v3/resolvers/mutation/emote.go
>  	user := ctx.Value("user").(*structures.User)
monkaS ?

2021-10-19 07:16 UTC, TroyDota commented on src/server/v3/gql-v3.go
> +		ctx := context.WithValue(context.Background(), helpers.UserKey, c.Locals("user")) // Add auth user to context
remove helpers and rather just use `utils.Key("user")`

2021-10-19 07:16 UTC, TroyDota commented on src/server/v3/gql-v3.go
> +			pipeline.Exec(ctx)
check errors?

2021-10-19 07:16 UTC, TroyDota commented on src/server/v3/helpers/keys.go
> +package helpers
Remove this file.

2021-10-19 07:16 UTC, TroyDota commented on src/server/v3/resolvers/query/emote.go
> +		quota:        ctx.Value(helpers.QuotaKey).(*helpers.Quota),
rather reference a `utils.Key` value.

2021-10-19 07:18 UTC, TroyDota commented on src/server/v3/gql-v3.go
> +			pipeline.HSet(ctx, fmt.Sprintf("%s:blocked-queries", instance.RedisPrefix), qh, clientIP)
why are we setting this value in the map?
This will never expire correct?

2021-10-19 07:38 UTC, AnatoleAM commented on src/server/v3/gql-v3.go
> +			pipeline.HSet(ctx, fmt.Sprintf("%s:blocked-queries", instance.RedisPrefix), qh, clientIP)
Is this solved by c135a06?

2021-10-19 10:22 UTC, merged